### ISSUE TITLE
[bug]spawn deaths

### ISSUE THREAD

**Issue by Coolguy1211** [caelan-douglas/tinybox#29]
**Version & Platform**
macOS custom build aka source build

**Description**
dieing on the official server when spawn protection ends

**Additional info, screenshots, logs**
Any additional info, including screenshots and logs, can be put here.

**Comment by caelan-douglas** [comment]
This is caused by the client version being different than the server version (ie. the client is on an up-to-date source build of 11.0pre but the server is on a version of 11.0pre from a few days prior, and thus they are incompatible). Right now, the server version differentiates between full releases (a client on beta 10.2 can't join a server on beta 10.3 or beta 11.0pre), but pre-release (source) builds are not differentiated.

In 88b344af05745bb2c911f9250a45e9f9398f316a there's now a warning when starting a pre-release build noting that joining servers may lead to unexpected behaviour. Later on I'd like to add a better way of differentiating versions (maybe based on commit hash) to prevent joining incompatible pre-release servers altogether.

**Comment by Tzav0002** [comment]
Cant wait for Tinybox version 11!

**Comment by Coolguy1211** [comment]
thanks
